name: PHP Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Verificar sintaxis PHP
      run: |
        find . -name "*.php" -exec php -l {} \;
